### ISSUE TITLE
Hangfire property keep logs from going from Serilog to SEQ

### ISSUE THREAD

**Issue by mack0196** [AnderssonPeter/Hangfire.Console.Extensions#8]
In some instances of SEQ (2021.3) that support hosted environments, logs are not getting to SEQ.

In my local instance of SEQ (2021.3) they do get though. My DevOps team tells me there is nothing in the SEQ instances that would reject\filter logs out.

In addition to the SEQ write to, have a console and debug logger for Serilog. The logs are showing in VS output (where they don't visualize the log property, just the message).

**Comment by AnderssonPeter** [comment]
Hi i have never used SEQ, but if it works locally but not when run in production I'm somewhat at a loss what could cause the issue. (check that the logging levels in appsettings.json and appsettings.development.json dont differ) 

I would need a project where you can recreate the issue otherwise i won't be of much help..

Are all messages lost or just some? is there a pattern to it? (example only warning and above are logged).

If you compile your test program and just run the exe without any ide, do the messages still get there?

**Comment by AnderssonPeter** [comment]
@mack0196 did you solve your issue?

**Comment by AnderssonPeter** [comment]
Closed because of no response
